# Generated by Django 2.2.5 on 2019-10-13 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/category')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ad')),
                ('email', models.EmailField(max_length=25, verbose_name='Email')),
                ('subject', models.CharField(max_length=50, verbose_name='Mövzu')),
                ('message', models.TextField(max_length=255, verbose_name='Mesaj')),
            ],
        ),
        migrations.CreateModel(
            name='Topproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ad')),
                ('price', models.IntegerField(verbose_name='Qiymət')),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255, verbose_name='Haqqında')),
                ('img', models.ImageField(upload_to='media/topproducts', verbose_name='Şəkil')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarix')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topproducts', to='djstore.Category', verbose_name='Kategoriyalar')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ad')),
                ('price', models.IntegerField(verbose_name='Qiymət')),
                ('number', models.IntegerField(max_length=15)),
                ('description', models.CharField(max_length=255, verbose_name='Haqqında')),
                ('img', models.ImageField(upload_to='media/product', verbose_name='Şəkil')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarix')),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='djstore.Category', verbose_name='Kateqoriyalar')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='djstore.Category')),
            ],
            options={
                'verbose_name': 'category Translation',
                'db_table': 'djstore_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
