# Generated by Django 2.2.5 on 2019-10-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_top', models.ImageField(upload_to='media/baners')),
                ('banner_left', models.ImageField(upload_to='media/baners')),
                ('banner_right', models.ImageField(upload_to='media/baners')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.IntegerField(),
        ),
    ]
