# Generated by Django 2.2.5 on 2019-10-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstore', '0002_auto_20191019_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banerleft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_left', models.ImageField(upload_to='media/bannersleft')),
            ],
        ),
        migrations.CreateModel(
            name='Banerright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_right', models.ImageField(upload_to='media/bannersright')),
            ],
        ),
        migrations.CreateModel(
            name='Banertop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_top', models.ImageField(upload_to='media/banerstop')),
            ],
        ),
        migrations.DeleteModel(
            name='Baner',
        ),
    ]
